### PR TITLE
Login

### PR DESCRIPTION
**Pull request by MaxChen102**
finished most of login view (exept for document listeners), use case and the interface adapters. please take a look and let me know what i need to change.

### CODE REVIEW

**Review by ChristopherLi05 — CHANGES_REQUESTED** [review]
Please remove your additions to the tabswitcher. We will look at it in a different pull request. Keep this to 
The command should be `git revert login~3..login`.

**Comment by MaxChen102** [comment]
Changes have been reverted, I will work on tab switcher on a separate branch.

**Review by ChristopherLi05 — APPROVED** [review]

**Review by ChristopherLi05 — CHANGES_REQUESTED** [review]
You never set logincontroller in loginview so buttons error out when you click
LoginInteractor is not correct. You should be checking if not null, not if return is equal to username (this will not always always be the case as well!)

**Comment by MaxChen102** [comment]
I have made new changes, please take a look. Also i think calculator state should have username or sessionid so login output data has somewhere to go

**Comment by ChristopherLi05** [comment]
You should be using UserManager

**Review by ChristopherLi05 — APPROVED** [review]

**Pull request merged**
