### PR TITLE
Added logout button to tabswitcher, changed button names

### PR DESCRIPTION
**Pull request by MaxChen102**
implemented logout button such that it takes the user back to signup

### CODE REVIEW

**Comment by ChristopherLi05** [comment]
don't do this lmao

**Review by ChristopherLi05 — CHANGES_REQUESTED** [review]
i made it this way for a reason. throw in another parameter if you must, but this was made purposely

**Comment by MaxChen102** [comment]
okok

**Comment by MaxChen102** [comment]
is this okay?

**Comment by ChristopherLi05** [comment]
This is still completely wrong lmao
```
            else if (pair.getValue() instanceof SignupViewState) {
                JButton button = new JButton("Log Out");
                button.setFont(new Font("arial", Font.PLAIN, 30));
                button.addActionListener(e -> viewManager.setView(pair.getKey()));
                this.add(button);
            }
```

Why are you even doing this. Just append an extra button to the end and make it set to login view or something

**Comment by MaxChen102** [comment]
is this what you meant?

**Comment by ChristopherLi05** [comment]
looks fine, someone else can also review it too

**Comment by Hiro2974** [comment]
The structure looks good. You added another button without modifying the previously exisiting codes shows how the structure itself is well designed.

**Pull request merged**
